### ISSUE TITLE
Error when running autoRotate

### ISSUE THREAD

**Issue by mattcodez** [GritDesign/node-jpegorientation#1]
NodeJS is crashing when trying to use autoRotate. I tried wrapping the call in a try/catch but it still crashes.

```
events.js:72
throw er; // Unhandled 'error' event
^
Error: spawn ENOENT
at errnoException (child_process.js:988:11)
at Process.ChildProcess._handle.onexit (child_process.js:779:34) 
```

**Comment by jeremycondon** [comment]
Sounds like its crashing within the compiled code.  What OS are you using and do you have a sample image/code that I can reproduce the bug with?

**Comment by mattcodez** [comment]
Running "Red Hat Enterprise Linux Server release 6.4 (Santiago)"

```
var jpegRotator = require("jpegorientation");
jpegRotator.autoRotate('image-71.jpg','image-71-2.jpg',function(err){
    err && console.error(err);
});
```

Image that I'm using in this snippet: http://i.imgur.com/rpJFBpS.jpg

**Comment by jeremycondon** [comment]
Do you have GraphicsMagick or ImageMagick installed.  jpegorientation is dependent on node 'gm' (https://github.com/aheckmann/gm) which requires GraphicsMagick or ImageMagick to be installed.  (see the gm github for more details)

**Comment by mattcodez** [comment]
Ah, no I did not. I just now installed ImageMagick but am still getting the same error so I'm guessing the issue is actually with gm not being able to call the ImageMagick programs.

**Comment by jeremycondon** [comment]
I usually have better luck with GraphicsMagick. Try that, if that 
doesn't work I can spin up a Redhat VM and see if I can reproduce. Its 
working fine for me on Ubuntu and OSX.
