### ISSUE TITLE
npm install (node-gyp rebuild) fails:

### ISSUE THREAD

**Issue by kanef** [GritDesign/node-jpegorientation#2]
`npm install jpegorientation` works on one of my Macs and not on another.  Am I doing something wrong, like failing to install something, or is it actually "problem with the jpegorientation package"?   All 125 of the other packages my project is using install without error.

```
% npm version | grep npm
  npm: '1.4.9',

% npm install
npm http GET https://registry.npmjs.org/jpegorientation
npm http 304 https://registry.npmjs.org/jpegorientation
npm http GET https://registry.npmjs.org/gm
npm http 304 https://registry.npmjs.org/gm

> jpegorientation@1.0.2 install /Users/work/NASA/WebStormProjects/Playbook/node_modules/jpegorientation
> node-gyp rebuild

  CXX(target) Release/obj.target/jpegexiforient/src/jpegexiforient.o
make: c++: No such file or directory
make: *** [Release/obj.target/jpegexiforient/src/jpegexiforient.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/work/NASA/WebStormProjects/Playbook/node_modules/jpegorientation
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! jpegorientation@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jpegorientation@1.0.2 install script.
npm ERR! This is most likely a problem with the jpegorientation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls jpegorientation
npm ERR! There is likely additional logging output above.
```

**Comment by jeremycondon** [comment]
Do you have the xcode command line development tools installed?  It looks like make can't find c++/gcc to build the binary.

**Comment by kanef** [comment]
Thanks for the quick reply.

Just before opening this issue I searched for XCode in the App Store and it showed it as being already installed.

```
% which gcc
/Applications/Xcode.app/Contents/Developer/usr/bin/gcc
% which c++
c++: Command not found.
```

**Comment by jeremycondon** [comment]
c++ should be installed with the command line tools, that's usually a separate install (from within Xcode).  See if this post helps: http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

**Comment by kanef** [comment]
I'm running MacOS 10.8.5.  The command given in that article for 10.9 doesn't work:  `code-select: Error: unknown command option '--install'.`  I also tried opening the Xcode GUI and searching for "command", "tool", and "install", and couldn't find anything.

What did you mean by the slash in "can't find c++/gcc"?  Did you mean it needs both, or that it would can't find either, or that it can use either but can't find either one?  Because it should have been able to find gcc.

**Comment by jeremycondon** [comment]
in 10.8.5 you had to manually install the command line tools in Xcode.  See: http://www.cyberciti.biz/faq/howto-apple-mac-os-x-install-gcc-compiler/

I wasn't sure which was required for the compilation, its all behind the scenes with node-gyp, however, it is complaining that the `c++` command is not there, so we need to resolve that.

**Comment by kanef** [comment]
Thanks!  That did the trick.

```
% rehash; which c++
/usr/bin/c++

% npm install
npm http GET https://registry.npmjs.org/jpegorientation
npm http 304 https://registry.npmjs.org/jpegorientation
npm http GET https://registry.npmjs.org/gm
npm http 304 https://registry.npmjs.org/gm

> jpegorientation@1.0.2 install /Users/work/NASA/WebStormProjects/Playbook/node_modules/jpegorientation
> node-gyp rebuild

  CXX(target) Release/obj.target/jpegexiforient/src/jpegexiforient.o
  SOLINK_MODULE(target) Release/jpegexiforient.node
  SOLINK_MODULE(target) Release/jpegexiforient.node: Finished
```
